baseurl = "https://monolithsplit.com"
languageCode = "en-us"
title = "monolithsplit.com | Learn how to decompose your old monolith into money-making microservices!"
content= "This stuff is good!"
theme = "zodkoo-dark"

[params]
  brandName = "MONOLITHSPL/T"

  # Main navigation
  [params.navigation]
    callToAction = "Notify me!"
    mobileNavToggle = "Toggle navigation"
    [[params.navigation.item]]
      text = "Why"
      link = "#why"
      defaultClass = "active"
    [[params.navigation.item]]
      text = "How"
      link = "#how"
    [[params.navigation.item]]
      text = "What"
      link = "#what"
    [[params.navigation.item]]
      text = "Plans"
      link = "#pricing"
    [[params.navigation.item]]
      text = "FAQ"
      link = "#faq"

  # Hero section
  [params.hero]
    title = "Stop throwing hard-earned money out the window."
    subtitle = "Get an expert-written report, tailor-made to your business needs! Break that monolith apart and migrate to microservices before your competitors."
    callToAction = "I need this!"
